site_name: Fcitx5 For Android
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: zh
  favicon: assets/ic_launcher_legacy_source.png
  logo: assets/ic_launcher_legacy_source.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
site_url: https://fcitx5-android.github.io

nav:
  - 主页: index.md
  - 安装: installation.md

repo_url: https://github.com/fcitx5-android/fcitx5-android.github.io

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist
