site_name: Fcitx5 For Android
site_description: Documentation for fcitx5-android
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: zh
  favicon: assets/ic_launcher_legacy_source.png
  logo: assets/ic_launcher_legacy_source.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
site_url: https://fcitx5-android.github.io

repo_name: fcitx5-android
repo_url: https://github.com/fcitx5-android/fcitx5-android

edit_uri: https://github.com/fcitx5-android/fcitx5-android.github.io/edit/master/docs/

copyright: Copyright &copy; 2022 Fcitx5 for Android Team

extra:
  social:
    - icon: simple/github
      link: https://github.com/fcitx5-android
      name: fcitx5-android on GitHub
    - icon: simple/matrix
      link: https://matrix.to/#/#fcitx5-android:mozilla.org
      name: fcitx5-android on Matrix
    - icon: simple/telegram
      link: https://t.me/+hci-DrFVWUM3NTUx
      name: fcitx5-android on Telegram
    - icon: simple/trello
      link: https://trello.com/w/fcitx5android
      name: fcitx5-android on Trello

nav:
  - 主页: index.md
  - 安装: installation.md
  - 常见问题: faq.md

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist
