name: Pull Request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: fcitx5-android
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build site
        run: nix develop --command mkdocs build --site-dir public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
